version: "3.8"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:11
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - pet_project_net

  security-app:
    image: security-app
    container_name: security-app
    hostname: security-app
    build:
      context: ../../application
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: 'jdbc:postgresql://postgres:5432/admin'
      spring.datasource.username: 'admin'
      spring.datasource.password: 'admin'
      spring.profiles.active: 'swagger-enabled,no-auth'
      jwt.access.token.ttl: '2'
      jwt.refresh.token.ttl: '720'
    ports:
      - "8081:8081"
    networks:
      - pet_project_net

volumes:
  vol_postgres:

networks:
  pet_project_net:
    driver: bridge